databases:
  - name: kisan-setu-db
    databaseName: kisansetu
    user: kisanuser
    plan: free

services:
  - type: web
    name: kisan-setu-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn kisan_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kisan-setu-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "kisan-setu-web.onrender.com,*.onrender.com"
